# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param synth.incrementalSynthesisCache C:/Users/Jorre/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-15328-DESKTOP-897IESA/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Jorre/VivadoProjects/Fulladder_Display/Fulladder_Display.cache/wt [current_project]
set_property parent.project_path C:/Users/Jorre/VivadoProjects/Fulladder_Display/Fulladder_Display.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/Jorre/VivadoProjects/Fulladder_Display/Fulladder_Display.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Jorre/VivadoProjects/Fulladder_Display/Fulladder_Display.srcs/sources_1/new/BCDto7SEG.vhd
  C:/Users/Jorre/VivadoProjects/Fulladder_Display/Fulladder_Display.srcs/sources_1/new/BINtoBCD.vhd
  C:/Users/Jorre/VivadoProjects/Fulladder_Display/Fulladder_Display.srcs/sources_1/new/DisplayDriver.vhd
  C:/Users/Jorre/VivadoProjects/Fulladder_Display/Fulladder_Display.srcs/sources_1/imports/new/fourbits_adder.vhd
  C:/Users/Jorre/VivadoProjects/Fulladder_Display/Fulladder_Display.srcs/sources_1/imports/new/fulladder.vhd
  C:/Users/Jorre/VivadoProjects/Fulladder_Display/Fulladder_Display.srcs/sources_1/new/Fulladder_Display.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Jorre/VivadoProjects/Fulladder_Display/Fulladder_Display.srcs/constrs_1/new/fulladder_display.xdc
set_property used_in_implementation false [get_files C:/Users/Jorre/VivadoProjects/Fulladder_Display/Fulladder_Display.srcs/constrs_1/new/fulladder_display.xdc]


synth_design -top Fulladder_Display -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Fulladder_Display.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Fulladder_Display_utilization_synth.rpt -pb Fulladder_Display_utilization_synth.pb"
